name: roco-pvp-lineup

services:
  roco-pvp-lineup:
    build:
      context: .
      dockerfile: Dockerfile
    image: roco-pvp-lineup:latest
    container_name: roco-pvp-lineup
    ports:
      - "9988:9988"
    volumes:
      - ./LuokePVPWebui:/app/LuokePVPWebui
    environment:
      NODE_ENV: production
      ADMIN_USER: admin
      ADMIN_PASS: "123"
    restart: unless-stopped
