name: rocom-pvp-battle-array--v2

services:
  rocom-pvp-battle-array-v2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rocom-pvp-battle-array--v2
    ports:
      - "9988:9988"
    volumes:
      - ./LuokePVPWebui:/app/LuokePVPWebui
    environment:
      NODE_ENV: production
      ADMIN_USER: admin
      ADMIN_PASS: admin123
    restart: unless-stopped
