export const SOCKET_EVENTS = {
  snapshot: 'snapshot',
  panelUpdate: 'panel:update',
  page4Update: 'page4:update',
  scoreboardUpdate: 'scoreboard:update',
  avatarUpdate: 'avatar:update',
  matchesUpdate: 'matches:update',
  stageUpdate: 'stage:update',
  page6Update: 'page6:update',
  page7Update: 'page7:update',
  page8Update: 'page8:update',
  page9Update: 'page9:update',
  nextgameUpdate: 'nextgame:update',
  profilesUpdate: 'profiles:update',
} as const;
